Тестовое задание номер 3
AlexeyPetrovskiy/java_pro pull request #2
Opened 2024-10-06 16:03 UTC by AlexeyPetrovskiy

2024-10-07 08:18 UTC, Alexandr056 requested changes
есть ряд комментариев, и плагины точно нужны в pom.xml?

2024-10-07 08:18 UTC, Alexandr056 commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +    private boolean isShutdown;
AtomicBoolean

2024-10-07 08:18 UTC, Alexandr056 commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +        Iterator<Runnable> iterator = listTask.iterator();
а чем реализованные методы для работы с листом не подошли?

2024-10-07 08:18 UTC, Alexandr056 commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +    public synchronized void execute(final Runnable task) {
синхронизироваться лучше по участкам кода, с монитором

2024-10-07 08:18 UTC, Alexandr056 commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +                return false;
ну это скорее получилась проверка а не остановка, для ожидания завершения нужно подумать в сторону join

2024-10-07 08:18 UTC, Alexandr056 commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +                if (taskToPerform != null) {
а если == null? 
тут стоит реализовать wait/notify

2024-10-09 15:11 UTC, AlexeyPetrovskiy commented
> есть ряд комментариев, и плагины точно нужны в pom.xml?

мавен quickstart архетип создает сразу с плагинами в pomнике. Не стал их трогать

2024-10-09 15:11 UTC, AlexeyPetrovskiy commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +    private boolean isShutdown;
поправил

2024-10-09 15:11 UTC, AlexeyPetrovskiy commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +        Iterator<Runnable> iterator = listTask.iterator();
Сделал через getFirst

2024-10-09 15:12 UTC, AlexeyPetrovskiy commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +    public synchronized void execute(final Runnable task) {
Done

2024-10-09 15:12 UTC, AlexeyPetrovskiy commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +                return false;
Реfлизовал через join

2024-10-09 15:12 UTC, AlexeyPetrovskiy commented on task3/src/main/java/ru/innotech/education/CustomThreadPool.java
> +                if (taskToPerform != null) {
реализовал wait notify

2024-10-10 07:26 UTC, Alexandr056 approved these changes

2024-10-12 17:20 UTC, merged